# Post Deploy Performance Testing Github Action Workflow

name: Performance-CGAP

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Deps
        run: make configure

      # Runs a set of commands using the runners shell
      - name: CI
        env:
          LOCUST_USER_CGAP: ${{ secrets.LOCUST_USER_CGAP }}
          LOCUST_PASS_CGAP: ${{ secrets.LOCUST_PASS_CGAP }}
        run: |
          make build
          make test
          make deploy-test-headless-cgap
