# Post Deploy Performance Testing Github Action Workflow

name: Performance-Fourfront 

# Controls when the action will run. 
on:
  # Scheduled daily 7am EST / 11am UTC
  schedule:
    - cron: "0 11 * * *"
  # Also can be run manually
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Install Deps
        run: make configure

      - name: CI
        env:
          LOCUST_USER: ${{ secrets.LOCUST_USER }}
          LOCUST_PASS: ${{ secrets.LOCUST_PASS }}
        run: |
          make build
          make test
          make deploy-test-headless-ff
